<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Registration;
use App\Enums\AttendingOption;

class AnniversaryRegistrationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $register = array(
            ['uuid' => 'ANNIV0001', 'firstname' => 'Amadeo Gabriel', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0002', 'firstname' => 'Amphy', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0003', 'firstname' => 'Cyrus', 'lastname' => 'Cinina', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0004', 'firstname' => 'Elaine', 'lastname' => 'Palabrica', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0005', 'firstname' => 'Gab', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0006', 'firstname' => 'Lience', 'lastname' => '', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0007', 'firstname' => 'Rhea Jean', 'lastname' => '', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0008', 'firstname' => 'Roselyn', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0009', 'firstname' => 'Ryza', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0010', 'firstname' => 'Zairah Mae', 'lastname' => 'Diaz', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0011', 'firstname' => 'Esmie', 'lastname' => 'Potente', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'ANNIV0012', 'firstname' => 'Gloria ', 'lastname' => 'Obispo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'ANNIV0013', 'firstname' => 'Jasmin ', 'lastname' => 'Buenaventura', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'ANNIV0014', 'firstname' => 'Marieta', 'lastname' => 'Batitis', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'ANNIV0015', 'firstname' => 'Zhia', 'lastname' => 'Ramos', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'ANNIV0016', 'firstname' => 'JT ', 'lastname' => 'Manansala', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CLB(Calamba)'],
            ['uuid' => 'ANNIV0017', 'firstname' => 'Kyle ', 'lastname' => 'Fajura', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'ANNIV0018', 'firstname' => 'Marco Ezekiel', 'lastname' => 'Lopez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'ANNIV0019', 'firstname' => 'May', 'lastname' => 'Palma', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M2 (Sta. Rosa)'],
            ['uuid' => 'ANNIV0020', 'firstname' => 'Michelle', 'lastname' => 'Tiamsing', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M5 (Liberty Homes)'],
            ['uuid' => 'ANNIV0021', 'firstname' => 'Keisha ', 'lastname' => 'Garachico', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'ANNIV0022', 'firstname' => 'Abrielle Regina ', 'lastname' => 'De Jesus', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'ANNIV0023', 'firstname' => 'Aileen', 'lastname' => 'Juanico', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'ANNIV0024', 'firstname' => 'Andrea Danielle', 'lastname' => 'De Jesus', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'ANNIV0025', 'firstname' => 'Danialle', 'lastname' => 'Padernal', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'ANNIV0026', 'firstname' => 'Ismael ', 'lastname' => 'Pastrano', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'ANNIV0027', 'firstname' => 'Kaleb Roy ', 'lastname' => 'Santillan', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'ANNIV0028', 'firstname' => 'Michelle', 'lastname' => 'De Jesus', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'ANNIV0029', 'firstname' => 'Paul', 'lastname' => 'De Jesus', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'ANNIV0030', 'firstname' => 'John Ralph ', 'lastname' => 'Basbanio', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'M9 (Bayanan)'],
            ['uuid' => 'ANNIV0031', 'firstname' => 'Czarina', 'lastname' => 'Chan', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'MNL (Manila)'],
            ['uuid' => 'ANNIV0032', 'firstname' => 'Eon', 'lastname' => 'Hapal', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'MNL (Manila)'],
            ['uuid' => 'ANNIV0033', 'firstname' => 'Nicholas', 'lastname' => 'Hernandez', 'registration_type' => 'Member','local_church' => 'Binan', 'category' => 'Adult', 'cluster_group' => 'MNL (Manila)'],
            ['uuid' => 'ANNIV0034', 'firstname' => 'Bernard', 'lastname' => 'Donato', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'None'],
            ['uuid' => 'ANNIV0035', 'firstname' => 'Eiler Jene', 'lastname' => 'Agasang', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'ANNIV0036', 'firstname' => 'Erwin ', 'lastname' => 'Sta Rosa', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'ANNIV0037', 'firstname' => 'Ayessa', 'lastname' => 'Ignacio', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0038', 'firstname' => 'Chloe Jane  ', 'lastname' => 'Delacruz', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0039', 'firstname' => 'Irie', 'lastname' => 'Flores', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0040', 'firstname' => 'Jake ', 'lastname' => 'Alayon ', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0041', 'firstname' => 'Jan Elias   ', 'lastname' => 'Mojica', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0042', 'firstname' => 'Marlyn', 'lastname' => 'Cabantog', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0043', 'firstname' => 'MJ', 'lastname' => 'Dela Cruz', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0044', 'firstname' => 'Ruby', 'lastname' => 'Ignacio', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0045', 'firstname' => 'Samatha ', 'lastname' => 'Castañaday', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0046', 'firstname' => 'Sean Mikeila', 'lastname' => 'Asis', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0047', 'firstname' => 'Treshell Aica', 'lastname' => 'Magbanua', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0048', 'firstname' => 'Tricia Ann', 'lastname' => 'Magbanua', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'ANNIV0049', 'firstname' => 'Rina', 'lastname' => 'Paramio', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'ANNIV0050', 'firstname' => 'Zairah', 'lastname' => '', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00002', 'firstname' => 'Melanie', 'lastname' => 'De Vera', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00005', 'firstname' => 'Alex', 'lastname' => 'Cello', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP00008', 'firstname' => 'Jake ', 'lastname' => 'Imperial', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00009', 'firstname' => 'Renz', 'lastname' => 'Tud', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00011', 'firstname' => 'KC ', 'lastname' => 'Birot', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP00012', 'firstname' => 'Victorie Merl', 'lastname' => 'Cabero', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'QC (Quezon City)'],
            ['uuid' => 'LAMP00013', 'firstname' => 'Roxanne', 'lastname' => 'Rufo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00020', 'firstname' => 'Nil', 'lastname' => 'De Vera', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00021', 'firstname' => 'April Joy', 'lastname' => 'Balane', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00027', 'firstname' => 'Tel', 'lastname' => 'Jose', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP00033', 'firstname' => 'Racquel', 'lastname' => 'Adlong', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP00034', 'firstname' => 'Emelita', 'lastname' => 'Adlong', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP00035', 'firstname' => 'Emeterio', 'lastname' => 'Adlong', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP00036', 'firstname' => 'Bryan ', 'lastname' => 'Sta Rosa', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00037', 'firstname' => 'Dexter', 'lastname' => 'Dio', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'LAMP00038', 'firstname' => 'Steph', 'lastname' => 'Sta Rosa', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00039', 'firstname' => 'Grace ', 'lastname' => 'Dio', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'LAMP00040', 'firstname' => 'Kevin ', 'lastname' => 'Tud', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00041', 'firstname' => 'Adam', 'lastname' => 'Guna', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'LAMP00042', 'firstname' => 'Ann', 'lastname' => 'Guna', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'LAMP00043', 'firstname' => 'Toby', 'lastname' => 'Madrid', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP00045', 'firstname' => 'Gary ', 'lastname' => 'Madrid', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP00046', 'firstname' => 'Shaila', 'lastname' => 'Madrid', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP00049', 'firstname' => 'Joey ', 'lastname' => 'Tud', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00052', 'firstname' => 'Karyll  ', 'lastname' => 'Halina', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00053', 'firstname' => 'Jhiro  ', 'lastname' => 'Gutierrez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00054', 'firstname' => 'Ericka', 'lastname' => 'Velasco', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00055', 'firstname' => 'May', 'lastname' => 'Halina', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00068', 'firstname' => 'Areane', 'lastname' => 'Arellano', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00071', 'firstname' => 'James  ', 'lastname' => 'Jagape', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00073', 'firstname' => 'Michael', 'lastname' => 'Arellano', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00075', 'firstname' => 'Gau  ', 'lastname' => 'Lingamen', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00076', 'firstname' => 'Marinel', 'lastname' => 'Lingamen', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00077', 'firstname' => 'Fourth', 'lastname' => 'Lingamen', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00081', 'firstname' => 'Remedios', 'lastname' => 'Mamauag', 'registration_type' => 'Member','local_church' => 'Isabela', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00082', 'firstname' => 'Jonathan ', 'lastname' => 'Untalan', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00083', 'firstname' => 'Ruby', 'lastname' => 'Fronda', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M2 (Sta. Rosa)'],
            ['uuid' => 'LAMP00084', 'firstname' => 'Paulene ', 'lastname' => 'Balisi', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00090', 'firstname' => 'EJ', 'lastname' => 'Delviar', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00092', 'firstname' => 'Jenny Rose ', 'lastname' => 'Comia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00096', 'firstname' => 'Linda ', 'lastname' => 'Valentin', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00097', 'firstname' => 'Rigil Kent', 'lastname' => 'Valentin', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00098', 'firstname' => 'Kazandra Maple ', 'lastname' => 'Valentin', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00099', 'firstname' => 'Isaias Jr', 'lastname' => 'Dela Cruz', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'None'],
            ['uuid' => 'LAMP00100', 'firstname' => 'Elvie ', 'lastname' => 'Dela Cruz', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CLB(Calamba)'],
            ['uuid' => 'LAMP00101', 'firstname' => 'Aizelle', 'lastname' => 'Bernardo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00102', 'firstname' => 'Edson Mickel', 'lastname' => 'Bernardo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00103', 'firstname' => 'Helen ', 'lastname' => 'Laureano', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00104', 'firstname' => 'Julianne Rose ', 'lastname' => 'Laureano', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00105', 'firstname' => 'Virginia Mari II', 'lastname' => 'Batitis', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00106', 'firstname' => 'Racy Joy', 'lastname' => 'Asis', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00107', 'firstname' => 'Lance Jordan ', 'lastname' => 'Asis', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00108', 'firstname' => 'Skylar', 'lastname' => 'Asis', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00109', 'firstname' => 'Rhean ', 'lastname' => 'Basbanio', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M9 (Bayanan)'],
            ['uuid' => 'LAMP00111', 'firstname' => 'Raymark', 'lastname' => 'Volante', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00112', 'firstname' => 'Tin', 'lastname' => 'Villaflor', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00113', 'firstname' => 'Maru', 'lastname' => 'Villaflor', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00120', 'firstname' => 'James ', 'lastname' => 'Mejia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00122', 'firstname' => 'Arlene', 'lastname' => 'Mejia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M6 (Cupang)'],
            ['uuid' => 'LAMP00123', 'firstname' => 'Edwin', 'lastname' => 'Mejia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M6 (Cupang)'],
            ['uuid' => 'LAMP00126', 'firstname' => 'Grace  ', 'lastname' => 'Rioveros', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00129', 'firstname' => 'Angge', 'lastname' => 'Dapitan', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00133', 'firstname' => 'Lilac Madison ', 'lastname' => 'Emague', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M6 (Cupang)'],
            ['uuid' => 'LAMP00134', 'firstname' => 'Christian  ', 'lastname' => 'Emague', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M6 (Cupang)'],
            ['uuid' => 'LAMP00135', 'firstname' => 'Nicole', 'lastname' => 'Andales', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M6 (Cupang)'],
            ['uuid' => 'LAMP00137', 'firstname' => 'Ivory ', 'lastname' => 'Emague ', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M6 (Cupang)'],
            ['uuid' => 'LAMP00143', 'firstname' => 'Jeanine ', 'lastname' => 'Balane', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00145', 'firstname' => 'Joycie ', 'lastname' => 'Ramos', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00146', 'firstname' => 'Dante', 'lastname' => 'Ramos', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'B1 (San Juan)'],
            ['uuid' => 'LAMP00170', 'firstname' => 'Marloun', 'lastname' => 'Aala', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP00171', 'firstname' => 'Angel', 'lastname' => 'Someros', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00172', 'firstname' => 'Mark', 'lastname' => 'Ong', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Tarlac'],
            ['uuid' => 'LAMP00173', 'firstname' => 'Shane', 'lastname' => 'Ong', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Tarlac'],
            ['uuid' => 'LAMP00190', 'firstname' => 'Jethro ', 'lastname' => 'Garcia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP00194', 'firstname' => 'Pia', 'lastname' => 'Evangelista', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00195', 'firstname' => 'Pio', 'lastname' => 'Evangelista', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00204', 'firstname' => 'Dante', 'lastname' => 'Tud', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Tarlac'],
            ['uuid' => 'LAMP00205', 'firstname' => 'Judea ', 'lastname' => 'Tud', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Tarlac'],
            ['uuid' => 'LAMP00206', 'firstname' => 'Maricel', 'lastname' => 'Tud', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Tarlac'],
            ['uuid' => 'LAMP00208', 'firstname' => 'Julie Pearl ', 'lastname' => 'Diaz', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00210', 'firstname' => 'Marion', 'lastname' => 'Francisco', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00211', 'firstname' => 'Christine Anne', 'lastname' => 'Cabantog', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00222', 'firstname' => 'Nikki', 'lastname' => 'Chua', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00223', 'firstname' => 'Fabian ', 'lastname' => 'Santos', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00224', 'firstname' => 'Jossan ', 'lastname' => 'Santos', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00225', 'firstname' => 'Sanbiel Faith', 'lastname' => 'Santos', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00227', 'firstname' => 'Pol ', 'lastname' => 'Someros', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00228', 'firstname' => 'Maria Bernadette', 'lastname' => 'Someros', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00230', 'firstname' => 'Riza', 'lastname' => 'Someros', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00233', 'firstname' => 'Lawrence ', 'lastname' => 'Alcordo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP00234', 'firstname' => 'Grace ', 'lastname' => 'Alcordo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP00255', 'firstname' => 'Morin', 'lastname' => 'Del Campo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M2 (Sta. Rosa)'],
            ['uuid' => 'LAMP00305', 'firstname' => 'Gwen ', 'lastname' => 'Hernandez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00306', 'firstname' => 'MJ', 'lastname' => 'Hernandez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00307', 'firstname' => 'Dess', 'lastname' => 'Concepcion', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP00322', 'firstname' => 'Marcus Ethan ', 'lastname' => 'Lopez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00323', 'firstname' => 'Marilou', 'lastname' => 'Lopez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00324', 'firstname' => 'Mark Alvert', 'lastname' => 'Lopez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00347', 'firstname' => 'Cedie', 'lastname' => 'Crebello', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M6 (Cupang)'],
            ['uuid' => 'LAMP00370', 'firstname' => 'Jovy ', 'lastname' => 'Singcoy', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'BGC'],
            ['uuid' => 'LAMP00373', 'firstname' => 'Keng ', 'lastname' => 'Tan', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00375', 'firstname' => 'Jonna ', 'lastname' => 'Salumbides', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00376', 'firstname' => 'Jianna ', 'lastname' => 'Salumbides', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00398', 'firstname' => 'Madeleine', 'lastname' => 'Mesina', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00452', 'firstname' => 'Chloe Kate', 'lastname' => 'Esteleydes', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP00451', 'firstname' => 'Weng', 'lastname' => 'Esteleydes', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP00464', 'firstname' => 'Celia', 'lastname' => 'Ngitngit', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00468', 'firstname' => 'Redalyn', 'lastname' => 'Sierra', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'LAMP00475', 'firstname' => 'Ireene ', 'lastname' => 'Viado', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00476', 'firstname' => 'Jonathan ', 'lastname' => 'Viado', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00486', 'firstname' => 'Rizaldy', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00502', 'firstname' => 'Julieta ', 'lastname' => 'Diaz', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M2 (Sta. Rosa)'],
            ['uuid' => 'LAMP00544', 'firstname' => 'Cherry', 'lastname' => 'Tiamsing', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M5 (Liberty Homes)'],
            ['uuid' => 'LAMP00550', 'firstname' => 'Mark', 'lastname' => 'Zapanta', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M5 (Liberty Homes)'],
            ['uuid' => 'LAMP00581', 'firstname' => 'Susan', 'lastname' => 'Velasquez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00593', 'firstname' => 'Zenaida', 'lastname' => 'Visaya', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00594', 'firstname' => 'Lolita ', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00596', 'firstname' => 'Esmael', 'lastname' => 'Sagayap', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00597', 'firstname' => 'Hannah Fhrancheska V. ', 'lastname' => 'Bandojo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00600', 'firstname' => 'Amparo', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00601', 'firstname' => 'Emily', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00602', 'firstname' => 'Berlita', 'lastname' => 'Diaz', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00603', 'firstname' => 'Rhizzalyn', 'lastname' => 'Lumabas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'Angono'],
            ['uuid' => 'LAMP00620', 'firstname' => 'Jayka ', 'lastname' => 'Mirasol', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'LAMP00621', 'firstname' => 'JC ', 'lastname' => 'Mirasol', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'LAMP00622', 'firstname' => 'Fe ', 'lastname' => 'Mirasol', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'LAMP00623', 'firstname' => 'Johnny ', 'lastname' => 'Mirasol', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M7 (Sucat)'],
            ['uuid' => 'LAMP00630', 'firstname' => 'Roy', 'lastname' => 'Santillan', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00632', 'firstname' => 'Khian Roy ', 'lastname' => 'Santillan', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00633', 'firstname' => 'Emil', 'lastname' => 'Pascual', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00634', 'firstname' => 'Mariflor (Kelvi)', 'lastname' => 'Pascual', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00635', 'firstname' => 'Ethan Kowji', 'lastname' => 'Pascual', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00636', 'firstname' => 'Euan Kenji', 'lastname' => 'Pascual', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00640', 'firstname' => 'Joshel ', 'lastname' => 'Villardo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00656', 'firstname' => 'Jumar ', 'lastname' => 'Mainit', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00679', 'firstname' => 'Leo ', 'lastname' => 'Robiños', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00690', 'firstname' => 'Shaniah', 'lastname' => 'Solver', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00692', 'firstname' => 'Juan Carlos ', 'lastname' => 'Realuyo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00693', 'firstname' => 'Mike', 'lastname' => 'Laureano', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00694', 'firstname' => 'Klaud ', 'lastname' => 'Laureano', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00695', 'firstname' => 'Clauselyn ', 'lastname' => 'Cuasay', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00696', 'firstname' => 'Freya Briella ', 'lastname' => 'Dellosa', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP00705', 'firstname' => 'Jerum  ', 'lastname' => 'Orobia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00710', 'firstname' => 'Paulo', 'lastname' => 'Sison', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'MNL (Manila)'],
            ['uuid' => 'LAMP00714', 'firstname' => 'Marilyn', 'lastname' => 'Realuyo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00722', 'firstname' => 'Tess', 'lastname' => 'Fernandez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00723', 'firstname' => 'Mark', 'lastname' => 'Fernandez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00728', 'firstname' => 'Paul Deolo', 'lastname' => 'Balisi', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00760', 'firstname' => 'Bing', 'lastname' => 'Santillan', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00772', 'firstname' => 'Aida', 'lastname' => 'Alumia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00796', 'firstname' => 'Irish ', 'lastname' => 'Sison', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'MNL (Manila)'],
            ['uuid' => 'LAMP00797', 'firstname' => 'Rolly', 'lastname' => 'Uy', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'B1 (San Juan)'],
            ['uuid' => 'LAMP00798', 'firstname' => 'Paul David', 'lastname' => 'Sison', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'MNL (Manila)'],
            ['uuid' => 'LAMP00817', 'firstname' => 'Fereyda ', 'lastname' => 'Clemente ', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00819', 'firstname' => 'Liam Rey ', 'lastname' => 'Clemente', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00820', 'firstname' => 'Laurence   ', 'lastname' => 'Clemente', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00822', 'firstname' => 'Kim ', 'lastname' => 'Imperial', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP2 (Brgy. UB)'],
            ['uuid' => 'LAMP00886', 'firstname' => 'Alexander', 'lastname' => 'Tablate', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP00913', 'firstname' => 'Gloria ', 'lastname' => 'Clemente ', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00916', 'firstname' => 'Janine Febie ', 'lastname' => 'Realuyo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00917', 'firstname' => 'Teresita', 'lastname' => 'Realuyo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP00920', 'firstname' => 'Imee ', 'lastname' => 'De Venecia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00921', 'firstname' => 'Stephanie Queen', 'lastname' => 'De Venecia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00925', 'firstname' => 'Jover ', 'lastname' => 'Fortaleza', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00927', 'firstname' => 'Shiela', 'lastname' => 'Villardo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00928', 'firstname' => 'Jojit ', 'lastname' => 'Villardo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00929', 'firstname' => 'Jojit Jr.  ', 'lastname' => 'Villardo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00931', 'firstname' => 'Praxedes ', 'lastname' => 'Opena', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00932', 'firstname' => 'Mark Angelo', 'lastname' => 'Lava', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00936', 'firstname' => 'Argel', 'lastname' => 'Hek', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00937', 'firstname' => 'Fermarie Janine ', 'lastname' => 'Hek', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00946', 'firstname' => 'Maegan', 'lastname' => 'Malayao', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00954', 'firstname' => 'Claire Ann Joyce', 'lastname' => 'Malayao', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00955', 'firstname' => 'Zenaida', 'lastname' => 'Malayao', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LAMP00964', 'firstname' => 'Cathy', 'lastname' => 'Ngitngit', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP00966', 'firstname' => 'Penny', 'lastname' => 'Gatmaitan', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP00970', 'firstname' => 'Anthony', 'lastname' => 'Trinos', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP00984', 'firstname' => 'Patrick ', 'lastname' => 'Custodio', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LAMP00983', 'firstname' => 'Jeramie ', 'lastname' => 'Tugay-Aragon', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'QC (Quezon City)'],
            ['uuid' => 'LAMP01015', 'firstname' => 'Darwin', 'lastname' => 'Birot', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'N/A'],
            ['uuid' => 'LAMP01062', 'firstname' => 'Pia Marchesa', 'lastname' => 'Desunia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP01063', 'firstname' => 'Leniel ', 'lastname' => 'Desunia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP01083', 'firstname' => 'Jazz ', 'lastname' => 'Flores', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CLB(Calamba)'],
            ['uuid' => 'LAMP01092', 'firstname' => 'Cynthia', 'lastname' => 'Bautista', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP4 (San Pedro / Bacoor / Parañaque)'],
            ['uuid' => 'LAMP01213', 'firstname' => 'Angeluz', 'lastname' => 'Lagrimas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'QC (Quezon City)'],
            ['uuid' => 'LAMP01218', 'firstname' => 'Vic Lorenz', 'lastname' => 'Nuñez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LAMP01241', 'firstname' => 'Macky', 'lastname' => 'Galvan', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP01299', 'firstname' => 'Ashley', 'lastname' => 'Mapalad', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP01300', 'firstname' => 'Ezekiel', 'lastname' => 'Jaug', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP01301', 'firstname' => 'Luke', 'lastname' => 'Jaug', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP01302', 'firstname' => 'Precious Ezrah', 'lastname' => 'Mapalad', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP01304', 'firstname' => 'Andrea Shane', 'lastname' => 'Alumia', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'CB (Carmona/Binan)'],
            ['uuid' => 'LAMP01310', 'firstname' => 'Alvie', 'lastname' => 'Pellodar', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'QC (Quezon City)'],
            ['uuid' => 'LAMP01311', 'firstname' => 'Maricris', 'lastname' => 'Ambas', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'QC (Quezon City)'],
            ['uuid' => 'LAMP01332', 'firstname' => 'Anna', 'lastname' => 'Tanael', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M5 (Liberty Homes)'],
            ['uuid' => 'LAMP01333', 'firstname' => 'Aaron Jude', 'lastname' => 'Tanael', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LAMP01433', 'firstname' => 'Joliza ', 'lastname' => 'Agasang', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'SP1 (Langgam / NHA / Batangas)'],
            ['uuid' => 'LAMP01438', 'firstname' => 'Jan Marlow ', 'lastname' => 'Manlulu', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LPMU00066', 'firstname' => 'Kate Murielle  ', 'lastname' => 'Lopez', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'LP (Las Pinas)'],
            ['uuid' => 'LPMU00086', 'firstname' => 'Aji', 'lastname' => 'Realuyo', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M1 (Soldiers/Bicutan)'],
            ['uuid' => 'LPMU00097', 'firstname' => 'Ikit ', 'lastname' => 'Santillan', 'registration_type' => 'Member','local_church' => 'Tarlac', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
            ['uuid' => 'LPMU00124', 'firstname' => 'Lourdes  ', 'lastname' => 'Tungol', 'registration_type' => 'Member','local_church' => 'Tarlac', 'category' => 'Adult', 'cluster_group' => 'M2 (Sta. Rosa)'],
            ['uuid' => 'LPMU00375', 'firstname' => 'Andrea Jeanine', 'lastname' => 'Hek', 'registration_type' => 'Member','local_church' => 'Tarlac', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LPMU00444', 'firstname' => 'Noelet John ', 'lastname' => 'Aragon', 'registration_type' => 'Member','local_church' => 'Tarlac', 'category' => 'Adult', 'cluster_group' => 'QC (Quezon City)'],
            ['uuid' => 'LPMU0085', 'firstname' => 'Leticia ', 'lastname' => 'Pascual', 'registration_type' => 'Member','local_church' => 'Tarlac', 'category' => 'Adult', 'cluster_group' => 'C3C4 (Dasma/Imus/Bacoor)'],
            ['uuid' => 'LPVA00010', 'firstname' => 'Meg', 'lastname' => 'Ileto', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'None'],
            ['uuid' => 'LAMP01089', 'firstname' => 'Timothy', 'lastname' => 'Padernal', 'registration_type' => 'Member','local_church' => 'Muntinlupa', 'category' => 'Adult', 'cluster_group' => 'M8 (Katarungan / Manggahan)'],
        );

        foreach ($register as $data) {
            $this->command->info('-------- registering guest ----------');

            $this->command->info('Full Name: ' . ($data['firstname']) . ' ' . ($data['lastname']));
            $this->command->info('Local Church: ' . $data['local_church']);

            $registration = Registration::create([
                'uuid' => $data['uuid'], 
                'email' => '',
                'firstname' => $data['firstname'],
                'lastname' => $data['lastname'],
                'fullname' => ($data['firstname']) . ' ' . ($data['lastname']),
                'facebook_name' => '',
                'registration_type' => $data['registration_type'],
                'local_church' => $data['local_church'],
                'cluster_group' => $data['cluster_group'],
                'country' => 'Philippines', 
                'category' => $data['category'], 
                'attending_option' => AttendingOption::Hybrid,
                'rate' => 0, 
                'payment_status' => 'Paid', 
                'booking_status' => 'Confirmed', 
                'with_awta_card' => 'yes',
                'can_book_rate' => 0, 
                'can_book_days' => 1, 
                'rebooking_limit' => 7, 
                'is_booking_bypassed' => 0, 
                'avail_new_lamp_id' => 'no', 
                'visitor_to_member' => null, 
                'medical_assistance_needed' => 'N/A', 
                'notes' => [], 
                'activities' => [], 
                'booking_activities' => [], 
                'booked_date' => null, 
                'is_received_hg' => null 
            ]);

            $registration->bookings()->create([
                'registration_uuid' => $registration->uuid,
                'slot_id' => 5,
                'local_church' => $registration->local_church,
                'status' => 'Confirmed'
            ]);

            $this->command->info('--------------- done '. $registration->id .' ----------------');
        }
    }
}
