<?php

namespace Database\Seeders;

use App\Models\Booking;
use App\Models\Registration;
use Illuminate\Database\Seeder;

class AutoBookSeeder2 extends Seeder
{
    public function run()
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        $bookMe = array(
            ['uuid'=>'GUEST0164', 'name'=>'Erick Amarante', 'local_church'=>'Binan', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0163', 'name'=>'Danilo Lerona', 'local_church'=>'Binan', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0003', 'name'=>'Ronald Abasula', 'local_church'=>'Binan', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0032', 'name'=>'Bea Villegas', 'local_church'=>'Binan', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0166', 'name'=>'Sonny Dela Cruz', 'local_church'=>'Binan', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'N'],
            ['uuid'=>'GUEST0173', 'name'=>'Roberto Jr Barcenas', 'local_church'=>'Binan', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'N'],
            ['uuid'=>'GUEST0178', 'name'=>'Cristiel Joy Hernandez', 'local_church'=>'Binan', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'N'],
            ['uuid'=>'GUEST0241', 'name'=>'Randy Miranda', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0245', 'name'=>'Maian Nacor', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0251', 'name'=>'Mairdy Miranda', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0252', 'name'=>'Samantha Miranda', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0253', 'name'=>'Fernan Cristo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0254', 'name'=>'Roseby Bustillo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0255', 'name'=>'Ma Luz Moncada Mangubat', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0256', 'name'=>'Charlie San Agustin', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0287', 'name'=>'Edwin Guanzon', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0288', 'name'=>'Thea Guanzon', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0289', 'name'=>'Aldwin Guanzon', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0290', 'name'=>'Ruben Francia', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0291', 'name'=>'Kyllie Santillan', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0292', 'name'=>'Katte Santillan', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0293', 'name'=>'Carlo Santillan', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0294', 'name'=>'Vanene Santillan', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0295', 'name'=>'Ronaldo Sayson', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0296', 'name'=>'Edelmira Sayson', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0062', 'name'=>'Xian Harley Garcia', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0186', 'name'=>'Vannessa Joyce Suelto', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'Y', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0187', 'name'=>'Vaughn Nhicolo Suelto', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0188', 'name'=>'Vernice Nhicyle Suelto', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0317', 'name'=>'Vernice Suelto', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0389', 'name'=>'Rica Palomares', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0390', 'name'=>'Gabriel Burgos', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0391', 'name'=>'Novie Mamitag', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0392', 'name'=>'Rosalina Marinas', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0393', 'name'=>'Alaiza Marinas', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0394', 'name'=>'Maria Christina Boligor', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0396', 'name'=>'Mickae Audrey Paulo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0397', 'name'=>'Regalado Paulo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0398', 'name'=>'Maria Theresa Paulo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0401', 'name'=>'Evelyn Chui', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0276', 'name'=>'Joseph Angelo Fabrigas', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0277', 'name'=>'Jhuris Mae Fabrigas', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0278', 'name'=>'Jhomar Fabrigas', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0279', 'name'=>'Dannielle Medenilla', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0280', 'name'=>'Ffrances Mikaela Blaza', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0285', 'name'=>'Rexielyn Reguero', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0139', 'name'=>'Jaime de Luna Jr.', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0140', 'name'=>'Joan de Luna', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0169', 'name'=>'Matt Jasper Colocado', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0170', 'name'=>'Althea Rein Martinez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0300', 'name'=>'Pauline Jean Bunda', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0301', 'name'=>'Kent Simon Bunda', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0303', 'name'=>'Jairus marion Bunda', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0304', 'name'=>'Jonnifer Bunda', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0335', 'name'=>'irene umila', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0336', 'name'=>'clarent bryce umila', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0337', 'name'=>'clint justine umila', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0123', 'name'=>'ARCENIA RITTER', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0153', 'name'=>'Sherwin Mirambino', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0054', 'name'=>'Roy Padayao', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0055', 'name'=>'Royent Padayao', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0057', 'name'=>'Annie may Abelis', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0058', 'name'=>'Denida Abeles', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0059', 'name'=>'Zhyvia Jane Catighod', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0379', 'name'=>'ROSE Castillo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0388', 'name'=>'Jelyn Flores', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0106', 'name'=>'Reenalyn Villapando', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0149', 'name'=>'Joseph Aala', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0150', 'name'=>'John Aala', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0151', 'name'=>'Myla Aala', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0152', 'name'=>'Dennis Aala', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0191', 'name'=>'Daylene Dioso', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0192', 'name'=>'Vilma Dioso', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0114', 'name'=>'Ricky Aviles', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0315', 'name'=>'Nikki Laquinario', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0316', 'name'=>'Joy Butarmos', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0344', 'name'=>'JOMARIE PARDINES', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0345', 'name'=>'JOHARRA AETHAN ROSE PARDINES', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0212', 'name'=>'CLARISE COLORICO', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0216', 'name'=>'ANABEL RAFAEL', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0281', 'name'=>'Gerry Rafael', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0282', 'name'=>'Jay Mabolo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0283', 'name'=>'Jasmine Joy Mabolo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0284', 'name'=>'JAYVIE MABOLO', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0209', 'name'=>'Abadiha Alamag', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0302', 'name'=>'Precy Deleon', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0305', 'name'=>'Kimberly Nicole Javier', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0327', 'name'=>'vhette vijar', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0328', 'name'=>'zl vijar', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0331', 'name'=>'rc vijar', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0237', 'name'=>'Gregorio Palomado', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0238', 'name'=>'Gregorio Palomado,  sr.', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0239', 'name'=>'Nerissa Palomado', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0240', 'name'=>'Rclyn Adena', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0242', 'name'=>'Jemalyn Palomado', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0243', 'name'=>'Jermilyn Palomado', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0244', 'name'=>'Adolfo Almiranez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0380', 'name'=>'Jonna Angela Torres', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0193', 'name'=>'Berckly Cabreros', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0233', 'name'=>'gantalao alexandra', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0306', 'name'=>'Analyn Sampaga', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0307', 'name'=>'Rich Anthony Sampaga', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0308', 'name'=>'Andrich Sampaga', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0309', 'name'=>'Richard Jr. Sampaga', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0310', 'name'=>'Rich Andrew Sampaga', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0311', 'name'=>'Riana Francesca Sampaga', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0312', 'name'=>'Francis Jay Buensalida', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0313', 'name'=>'sophia jaden buensalida', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0314', 'name'=>'Jerry Medriano', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0334', 'name'=>'Rowena Gutay', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0060', 'name'=>'Maria Catherine Ramos', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0324', 'name'=>'Danica Miralles', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0325', 'name'=>'Jheannica Jillian Magbanua', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0352', 'name'=>'Melanie Incomio', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0353', 'name'=>'John Cyrus Pantaleon', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0195', 'name'=>'Alex Yefremov', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0246', 'name'=>'Jayson Fajardo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0247', 'name'=>'Rose Fajardo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0248', 'name'=>'Ronalyn Fajardo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0249', 'name'=>'Jenny Marantal', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0338', 'name'=>'Luis Christopher Bulatao', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0340', 'name'=>'Cristopher Bulatao', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0348', 'name'=>'Princess Sagot', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0385', 'name'=>'Nhorfaisahlyn Baratamai', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0386', 'name'=>'Jalilah Lanaha', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0387', 'name'=>'Jelyn Landicho', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0071', 'name'=>'Enrico Suazo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0078', 'name'=>'Carmie Magdaong', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0096', 'name'=>'Randy Valenzuela', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0097', 'name'=>'Anica Faith Magdaong', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0116', 'name'=>'Lochel Malibiran', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0125', 'name'=>'Rodrick Anton Olivarez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0127', 'name'=>'Rouel Olivarez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0128', 'name'=>'Annah Sarvida Olivarez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0129', 'name'=>'Harold Hondanero', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0131', 'name'=>'Hanze Zhairedj Hondanero', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0132', 'name'=>'Aaliah Asrielle Duron', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0133', 'name'=>'Sammy Dagayloan', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0134', 'name'=>'Haze Cali Hondanero', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0135', 'name'=>'Cathaleya Zenalie Dilay', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0136', 'name'=>'Jaelen Ross Dorado', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0160', 'name'=>'Rijie Valerio', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0179', 'name'=>'Limuel Nequinto', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0180', 'name'=>'Felicisimo Doncansil', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0181', 'name'=>'Dannah Doncansil', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0250', 'name'=>'Helen Espinola', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0297', 'name'=>'Rowena Villegas', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0299', 'name'=>'Jerome Eguarras', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0362', 'name'=>'Maria Stela Alindogan', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0365', 'name'=>'Emmanuel Aldwin Hernandez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0366', 'name'=>'Allen Kirvee Hernandez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0367', 'name'=>'Jan Isabelle Hernandez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0368', 'name'=>'Yhuann May Olivarez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0369', 'name'=>'Ace Cali Hondanero', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0370', 'name'=>'Jhonard Duron', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0375', 'name'=>'Che Salvador', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0376', 'name'=>'Reoona Eliz Olivarez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0381', 'name'=>'Lotis Sandoval', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0410', 'name'=>'Shynie De Asis', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0026', 'name'=>'Vlagne Anthony Viluan', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0030', 'name'=>'Jermaine Cruzana', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0031', 'name'=>'Princess Eirel Corales', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0419', 'name'=>'Vince Fernandez', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0403', 'name'=>'Phillip Young', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0404', 'name'=>'PALOMA YOUNG', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0382', 'name'=>'Hazel Beatingo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0383', 'name'=>'Zhantal Mae Beatingo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0384', 'name'=>'Samantha Beatingo', 'local_church'=>'Canlubang', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0120', 'name'=>'Mylon Borromeo', 'local_church'=>'Dasmarinas', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0184', 'name'=>'Ronel Estrada', 'local_church'=>'Dasmarinas', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0185', 'name'=>'Mary Ann Ibana', 'local_church'=>'Dasmarinas', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0161', 'name'=>'Austin Lumot', 'local_church'=>'Dasmarinas', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0165', 'name'=>'Khian Gallardo', 'local_church'=>'Dasmarinas', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0121', 'name'=>'Rean Mamauag', 'local_church'=>'Muntinlupa', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0265', 'name'=>'Kristofferson Espino', 'local_church'=>'Muntinlupa', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0264', 'name'=>'Rochie Mae Espino', 'local_church'=>'Muntinlupa', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0014', 'name'=>'Emmanuel John Soliveres', 'local_church'=>'Muntinlupa', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0013', 'name'=>'Mac Joener Macha', 'local_church'=>'Muntinlupa', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0074', 'name'=>'Janet Basbanio', 'local_church'=>'Muntinlupa', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0346', 'name'=>'Gringo Ibardaloza', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0350', 'name'=>'Piel Bassig', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0412', 'name'=>'Eurhis Arsmontt Valdellon', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0413', 'name'=>'Eurhis Arthur Valdellon', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0357', 'name'=>'German Paelmo', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0358', 'name'=>'Ana Alia Paelmo', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0359', 'name'=>'Amiya Paelmo', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0360', 'name'=>'Hanna Hiloma', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0361', 'name'=>'Janel Fernandez', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0364', 'name'=>'Lorna Alfrerez', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0402', 'name'=>'Arnold Tanay', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0416', 'name'=>'Mary Grace Sarmiento', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0417', 'name'=>'John Joshua Padallan', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0418', 'name'=>'Albert Padallan', 'local_church'=>'Pateros', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'N', 'day_4'=>'N'],
            ['uuid'=>'GUEST0045', 'name'=>'Yuri Lubao', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0010', 'name'=>'Romel Glori', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0145', 'name'=>'Helen Franco', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0144', 'name'=>'Jose Franco', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0023', 'name'=>'Shamara Mae Belmonte', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0034', 'name'=>'Paula  Simon', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0048', 'name'=>'Lourdes Gutierrez ', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0053', 'name'=>'Luie  Austria', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0065', 'name'=>'Cecile Laquindanum', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0066', 'name'=>'Gener Laquindanum ', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0143', 'name'=>'Jovelyn Tagalog', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0012', 'name'=>'Wilfredo Tiamzon', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0070', 'name'=>'Adelaida Tiamzon', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'N', 'day_3'=>'Y', 'day_4'=>'Y'],
            ['uuid'=>'GUEST0159', 'name'=>'Shanna Angela Guillermo ', 'local_church'=>'Tarlac', 'day_1'=>'N', 'day_2'=>'Y', 'day_3'=>'Y', 'day_4'=>'N'],
            ['uuid'=>'GUEST0061', 'name'=>'Angel Roasol', 'local_church'=>'Isabela', 'day_1'=>'N', 'day_2'=>'Y', 'day_3'=>'Y', 'day_4'=>'N'],
        );

        foreach ($bookMe as $data) {
            $this->command->info('---------------- booking guest (adult) ---------------');
            
            Booking::where('registration_uuid', $data['uuid'])->delete();

            $registration = Registration::where('uuid', $data['uuid'])->where('attending_option', 'Online')->first();

            if ($registration) {
                $registration->update(['attending_option' => 'Hybrid', 'can_book' => true]);
            }

            $this->command->info('Guest #: ' . $data['uuid'] . ' Full Name: ' . $data['name']);

            $dateToBeBooked = [];
            $booked_log = 'Booked Day(s): ';
            for ($x = 1; $x <= 4; $x++) {
                if ($data['day_' . $x] === 'Y') {
                    $booked_log .= 'Day ' . $x . ' ';
                    array_push($dateToBeBooked, [
                        'registration_uuid' => $data['uuid'],
                        'slot_id' => $x + 4,
                        'local_church' => $data['local_church']
                    ]);
                }
            }

            Booking::insert($dateToBeBooked);

            $this->command->info('Booked Day(s): ' . $booked_log);
            $this->command->info('-------------------------- done ----------------------');
        }
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
