<?php

namespace Database\Seeders;

use App\Models\Booking;
use App\Models\Registration;
use Illuminate\Database\Seeder;

class AutoBookSeeder5 extends Seeder
{
    public function run()
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        $bookMe = array(
            ['uuid'=>'LPDA00007', 'name'=>'Maila Gomez', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00008', 'name'=>'Sheena mae Neri', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00012', 'name'=>'Elmer Navarro', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00013', 'name'=>'Edith Navarro', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00014', 'name'=>'Samantha Navarro', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00015', 'name'=>'Shuck Navarro', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00016', 'name'=>'Shanon Navarro', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00017', 'name'=>'Danilo Montemayor', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00019', 'name'=>'Disah Montemayor', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00020', 'name'=>'Danine Monte mayor', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00021', 'name'=>'Daryl Valles', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00023', 'name'=>'Tricia mae Largo', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00024', 'name'=>'Rolly Fresco', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00027', 'name'=>'Dianne Baltazar', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00028', 'name'=>'Myka Baltazar', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00031', 'name'=>'Franz Ashley Lianza', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00033', 'name'=>'Ellah Jerish Velasco', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00034', 'name'=>'Jamica Rocero', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00035', 'name'=>'Neria Angeles', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00036', 'name'=>'Almira Lianza', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00037', 'name'=>'Nathan Lianza', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00038', 'name'=>'Abasia Gabrielle Lianza', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00039', 'name'=>'Anjeanette Fernandez', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00041', 'name'=>'Amy Fernandez', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00042', 'name'=>'Brendan Valles', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00043', 'name'=>'Rutchel Borromeo', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00044', 'name'=>'Desire Valles', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00045', 'name'=>'Barbario Valles', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00046', 'name'=>'Arthur Fernandez', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00051', 'name'=>'Shekinah jem Velasco', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00052', 'name'=>'Jerielle Velasco', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00053', 'name'=>'Princess Neri', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00055', 'name'=>'Rommel Melgazo', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00056', 'name'=>'Florifes Melgazo', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00063', 'name'=>'Angel Fernandez', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00070', 'name'=>'Sharina Pensol', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00071', 'name'=>'Sonia Pensol', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00073', 'name'=>'Terence Claire Largo', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00110', 'name'=>'Kurt Ahron Joaquin', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00111', 'name'=>'Johnrex esponilla', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00112', 'name'=>'Johnrey M.esponilla', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00114', 'name'=>'Reyse esponilla', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00138', 'name'=>'Mary ann Ellis', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00145', 'name'=>'Dareem Jost Tolentino', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00146', 'name'=>'Juanito esponilla', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPIS00001', 'name'=>'Fatima Trinidad', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00002', 'name'=>'Charry May Trinidad', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00003', 'name'=>'Kings Lee Aeron Yu', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00004', 'name'=>'Oswaldo Larugal', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00005', 'name'=>'Nenita Larugal', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00006', 'name'=>'Ralph Jayson Ochoa', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00007', 'name'=>'Pauline Bautista', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00011', 'name'=>'John Garo', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00013', 'name'=>'Cherry Pabigayan', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00014', 'name'=>'Serina Rapat', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00016', 'name'=>'Irish Princess Uy', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00020', 'name'=>'Rudy Trinidad', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00021', 'name'=>'Zyron Kyle Pontillas', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00022', 'name'=>'Ahmad Macapasir', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00023', 'name'=>'Jenny Mae Culalabe', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00024', 'name'=>'Shirlon Valdez', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00026', 'name'=>'Janine Marie Macdon', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00027', 'name'=>'Jan Mico Macdon', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00028', 'name'=>'Iluminada Larugal', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00029', 'name'=>'Nicole Larugal', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00030', 'name'=>'Mark Jiroh Galiza', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00034', 'name'=>'Jan Nicolai Macdon', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00040', 'name'=>'Hannah Grace Dizon', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00041', 'name'=>'Arlene Trinidad', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00042', 'name'=>'Rodolfo Trinidad', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00049', 'name'=>'Tricha May Co', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00050', 'name'=>'Gina Co', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00051', 'name'=>'Sharon Ochoa', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00052', 'name'=>'Cherie Ann Valdez', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00054', 'name'=>'Jewel Dane Gabriel', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPTA00006', 'name'=>'Marjessa Santana Alcibar', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00007', 'name'=>'Susan santana', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00008', 'name'=>'Marie Jezzel Santana', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00009', 'name'=>'Marjelyn Manalo', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00013', 'name'=>'Teresita Encarnacion', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00014', 'name'=>'Leonor Alcibar', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00015', 'name'=>'Juanito Encarnacion', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00016', 'name'=>'Jannele Dialino', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00018', 'name'=>'Mark Ong', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00019', 'name'=>'Vilma Ong', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00020', 'name'=>'Ed Ong', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00022', 'name'=>'Kimberlyn Alcibar Franco', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00023', 'name'=>'Veronica Cunanan', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00025', 'name'=>'Allen Francisco Laquindanum', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00026', 'name'=>'Paulcarlos Casupanan', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00031', 'name'=>'Mark Jerald T. Santana', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00032', 'name'=>'Carmen Mangrobang', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00033', 'name'=>'Crystal Go', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00034', 'name'=>'Joseph Alcibar', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00036', 'name'=>'Michaelcasupanan', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00040', 'name'=>'Jomarie Tagalog', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00041', 'name'=>'John Robert Lu', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00042', 'name'=>'Jharianney Sydney Dialino', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00043', 'name'=>'Jhanel Santos Manalo', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00044', 'name'=>'Hazel Bianca Garcia', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00045', 'name'=>'Joseph bayron', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00049', 'name'=>'Editha Dialino', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00050', 'name'=>'Reymon Manalo', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00051', 'name'=>'Carla Calaber', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00052', 'name'=>'Jenro John Puno', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00059', 'name'=>'Marie Stella Casupanan', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00060', 'name'=>'Harvey Mangrobang', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00061', 'name'=>'Alfred Tiamzon', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00062', 'name'=>'Mark Gabriel Belmonte', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00063', 'name'=>'Marnie Sebastian', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00067', 'name'=>'Jasmin Laza', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00069', 'name'=>'Marn Garcia', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00072', 'name'=>'Kallil Marin', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00073', 'name'=>'Merry Julianne Marin', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00076', 'name'=>'Luisa Palaganas Catap', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00077', 'name'=>'Aezel Cortez Gutierrez', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00083', 'name'=>'Remedios Lu', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00086', 'name'=>'Maria Luisa Laquindanum', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00087', 'name'=>'Princess Cunanan', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00094', 'name'=>'Sienna Ong', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00095', 'name'=>'KIa an Tundayag Lu', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00097', 'name'=>'Jan Wilson Sicat', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00098', 'name'=>'Maria Elaiza Garcia', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00099', 'name'=>'Theresa Belmonte', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00101', 'name'=>'Mark Joseph Belmonte', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00102', 'name'=>'Vilma Estigoy', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00103', 'name'=>'Jessamae Moldero', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00105', 'name'=>'Riza Mae Laquindanum', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00109', 'name'=>'Zarah Guillermo', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00110', 'name'=>'Krystal Jade Agpangan', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00111', 'name'=>'Althea Mae Malaqui Estavillo', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00112', 'name'=>'Joana Ericka Estavillo', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00113', 'name'=>'Kristina Cassandra Estavillo', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00114', 'name'=>'Noel Guillermo', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00118', 'name'=>'Rafael Cayabyab Tapulayan', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00119', 'name'=>'Gerard Austria Mangacu', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00121', 'name'=>'Jacob Sicat', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00130', 'name'=>'Neil Distrito', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00137', 'name'=>'Nino Laquindanum', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00139', 'name'=>'Nina Dela Cruz', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00140', 'name'=>'Ethan Pasion', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00143', 'name'=>'Judy Ann Marin', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00144', 'name'=>'Errol Marin', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00145', 'name'=>'Paula Sotto', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00146', 'name'=>'Aris Sicat', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00150', 'name'=>'Nicole Garcia', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00152', 'name'=>'Shaira shane', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00159', 'name'=>'Nicholas Gozum', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00132', 'name'=>'Joselito Birot', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00019', 'name'=>'Elvira Birot', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00010', 'name'=>'Alexander Cello', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00142', 'name'=>'Jenica Cello', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00107', 'name'=>'Ernesto Garcia', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00029', 'name'=>'Myrna Garcia', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPVA00015', 'name'=>'Gina Dolz', 'local_church'=> 'Valenzuela', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPIS00009', 'name'=>'Marloun Aala', 'local_church'=> 'Isabela', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00116', 'name'=>'Agnes Aala', 'local_church'=> 'Isabela', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00011', 'name'=>'Jose Dante Tud', 'local_church'=> 'Tarlac', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00010', 'name'=>'Maricel Tud', 'local_church'=> 'Tarlac', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPPA00021', 'name'=>'Marilou Camacho', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPPA00070', 'name'=>'Jocelyn Malbas', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPPA00071', 'name'=>'Fidel Malbas', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPMU00001', 'name'=>'Isaias Jr. Dela Cruz', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00002', 'name'=>'Elvie Dela Cruz', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00105', 'name'=>'Paulo Sison', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00106', 'name'=>'Ma. Criselda Sison', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00107', 'name'=>'Apolinario Someros', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00253', 'name'=>'Riza Someros', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00050', 'name'=>'Pio Evangelista', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00121', 'name'=>'Joselito Tud', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00122', 'name'=>'Amelia Tud', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00067', 'name'=>'Gary Madrid', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00068', 'name'=>'Divine Madrid', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00001', 'name'=>'Julio Mella', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00002', 'name'=>'Jennifer Mella', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00046', 'name'=>'Ronald Czerny Pumanes', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00047', 'name'=>'Evangelina Pumanes', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00202', 'name'=>'Larry Silva', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00201', 'name'=>'Alma Silva', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00026', 'name'=>'Roger Martinez', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00023', 'name'=>'Angeles Martinez', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00040', 'name'=>'Orsos Gerald', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00039', 'name'=>'Orsos Mia', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00123', 'name'=>'Oliver Orlando', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00124', 'name'=>'Oliver Jennifer', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00006', 'name'=>'Jerome Velasco', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00032', 'name'=>'Michelle Velasco', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00002', 'name'=>'Piolo Jirah Tuliao', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPDA00001', 'name'=>'Eddie Tuliao', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00012', 'name'=>'Judea Tud', 'local_church'=> 'Tarlac', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00031', 'name'=>'KLAUD LAUREANO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00038', 'name'=>'NIL DE VERA', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00022', 'name'=>'CRIS ANN JOSE', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00064', 'name'=>'GAUDENCIO LINGAMEN III', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00065', 'name'=>'MARINEL LINGAMEN', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00008', 'name'=>'MICHAEL ARELLANO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00268', 'name'=>'JIA VINLUAN', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPBI00125', 'name'=>'DEXTER CONCEPCION', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00432', 'name'=>'JAZREAL BALANAY', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00188', 'name'=>'DARYL GUTIERREZ', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00284', 'name'=>'JAMES JAGAPE', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00299', 'name'=>'ANGELO LAGRIADA', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00209', 'name'=>'MARK DANIEL REMUGAT', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00071', 'name'=>'JUMAR TOLEDO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00064', 'name'=>'JESON GARCIA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00323', 'name'=>'PAULENE BALISI', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00014', 'name'=>'RHEAN BASBANIO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00205', 'name'=>'AGATHA PAJENADO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00259', 'name'=>'ERICKA VELASCO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00327', 'name'=>'NOEL BUQUID', 'local_church'=> 'Canlubang', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00486', 'name'=>'KAEZLE CUETO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00009', 'name'=>'AREANE ARELLANO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00062', 'name'=>'JETHRO GARCIA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00063', 'name'=>'JM GARCIA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00263', 'name'=>'ADAM GUNA', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPPA00001', 'name'=>'AMOR ABAD', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPVA00007', 'name'=>'JAMIE BIROT', 'local_church'=> 'Valenzuela', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00041', 'name'=>'JULIE PEARL DIAZ', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00030', 'name'=>'KARISSA MELCHOR', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00070', 'name'=>'JENNILYN MARIN', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00101', 'name'=>'RACHEL ANN GARCIA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00033', 'name'=>'AMY JOSE', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00007', 'name'=>'BEVERLY DELA CRUZ', 'local_church'=> 'Binan', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00020', 'name'=>'JULIE CELLO', 'local_church'=> 'Binan', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPVA00010', 'name'=>'MEG ILETO', 'local_church'=> 'Valenzuela', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00057', 'name'=>'DARIUSE ANDINO', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00115', 'name'=>'WENG DELOS SANTOS', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPPA00067', 'name'=>'ANGIE CAMACHO', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPPA00054', 'name'=>'JAVIER SANCHEZ', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'Y'],
            ['uuid'=>'LPPA00066', 'name'=>'KENJIE BUENAVENTURA', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'Y'],
            ['uuid'=>'LPPA00072', 'name'=>'ANDY ESCOTOTO', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPCA00077', 'name'=>'MARIE AMOLAR', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00154', 'name'=>'DELY AALA', 'local_church'=> 'Canlubang', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'N', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00166', 'name'=>'AMY AMLOG', 'local_church'=> 'Canlubang', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'N', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00230', 'name'=>'DORCAS URGELLES', 'local_church'=> 'Canlubang', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'N', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00099', 'name'=>'PRINCESS EVASCO', 'local_church'=> 'Canlubang', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPMU00092', 'name'=>'ROXANNE ADEVARUFO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00008', 'name'=>'BHELLA HIDALGO', 'local_church'=> 'Canlubang', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPMU00024', 'name'=>'ANNA VERONICA CHUA', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00079', 'name'=>'JERUM OROBIA', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00010', 'name'=>'LANIE ATIENZA', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00072', 'name'=>'JOYCE MALAYAO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00164', 'name'=>'BING SANTILLAN', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPMU00136', 'name'=>'MARU VILLAFLOR', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00106', 'name'=>'KATE GARCIA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00034', 'name'=>'CAMILLE ALMEIDA', 'local_church'=> 'Binan', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPPA00007', 'name'=>'JEAN BAUTISTA', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPPA00060', 'name'=>'ARLO VALDELLON', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPMU00391', 'name'=>'JEN LAGORRA', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00013', 'name'=>'MICAELLA RODEL', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00134', 'name'=>'VIADO, JONG', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00135', 'name'=>'VIADO, IREENE', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00100', 'name'=>'SANTOS, JOSSAN', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00075', 'name'=>'ROSE ARCIAGA', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00213', 'name'=>'ARLENE SUNGA', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00176', 'name'=>'CLAUSELYN CUASAY', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00103', 'name'=>'MICHELLE SHROCK', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00274', 'name'=>'TIMOTHY PADERNAL', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00066', 'name'=>'KATE LOPEZ', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00196', 'name'=>'JAYKA MIRASOL', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00048', 'name'=>'WENG ESTEYLEDES', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00313', 'name'=>'CHLOE ESTEYLEDES', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00040', 'name'=>'ALDEN GARCIA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00059', 'name'=>'ALMA TIAMSING', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00046', 'name'=>'ANGEL ENDRIGA', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00254', 'name'=>'ARABELLE PEÑAREDONDA-PUMANES', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00101', 'name'=>'INAH JEUNE', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00031', 'name'=>'JANISSE MELLA', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00225', 'name'=>'JAZZ MELLA', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00105', 'name'=>'JOCHELLE GUTIERREZ', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00199', 'name'=>'MELANIE M NGITNGIT', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00093', 'name'=>'MIKE SALUMBIDES', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00168', 'name'=>'NICOLE ANDALES', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00392', 'name'=>'RACHEL MAE HIDALGO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00003', 'name'=>'RACQUEL ADLONG', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00070', 'name'=>'SHAILA GAIN MADRID', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00201', 'name'=>'VIC LORENZ NUÑEZ', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00042', 'name'=>'DEXTER DIO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00120', 'name'=>'TIN TUD', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00080', 'name'=>'CARLO BALLESTEROS', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00045', 'name'=>'JONATHAN PUMANES', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00244', 'name'=>'KAREN TAN', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00083', 'name'=>'DAN RAMOS', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00085', 'name'=>'YUAN REALUYO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00184', 'name'=>'ROMMEL FRANCISCO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00025', 'name'=>'JOYCIE RAMOS', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00355', 'name'=>'MARK VINCENT GALVAN', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00105', 'name'=>'KEVIN BIROT', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00032', 'name'=>'TEL JOSE', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00096', 'name'=>'FERNAN CAPITO', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00130', 'name'=>'ABRAM FRIANEZA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00041', 'name'=>'MARJ FRIANEZA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00124', 'name'=>'DREXLER CONCEPCION', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00125', 'name'=>'JONATHAN UNTALAN', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPPA00056', 'name'=>'SISA SORIANO', 'local_church'=> 'Pateros', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPBI00045', 'name'=>'DIANE FRIANEZA', 'local_church'=> 'Binan', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPBI00112', 'name'=>'JOHANSE BONIFACIO', 'local_church'=> 'Binan', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPBI00123', 'name'=>'MICCA ALAYON', 'local_church'=> 'Binan', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPCA00121', 'name'=>'JILL ANNE ARCIAGA', 'local_church'=> 'Canlubang', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPTA00060', 'name'=>'HARVEY MANGROBANG', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPIS00025', 'name'=>'ROSE ANN BALDAMUERTE', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPVA00020', 'name'=>'MARINELLE VIADO', 'local_church'=> 'Valenzuela', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPVA00006', 'name'=>'JORINE NARIO', 'local_church'=> 'Valenzuela', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'N'],
            ['uuid'=>'LPMU00272', 'name'=>'JAKE IMPERIAL', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00111', 'name'=>'BRYAN SANTA ROSA', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00039', 'name'=>'KEY ANN GARCIA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00061', 'name'=>'MICHAEL LAUREANO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00017', 'name'=>'JOHN MICHAEL ROBLES', 'local_church'=> 'Binan', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00398', 'name'=>'VIRGINIA MARI (BERJ) BATITIS', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00032', 'name'=>'KIM IMPERIAL', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00058', 'name'=>'MJ HERNANDEZ', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00230', 'name'=>'KARL LORENZ TUD', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00012', 'name'=>'JUDIE LABRADOR', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00143', 'name'=>'JEANINE BELANE', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00081', 'name'=>'WENDY AGUINALDO', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00030', 'name'=>'LINDA VALENTIN', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00004', 'name'=>'DHAZLE DE VERA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00084', 'name'=>'ROSE DALAWANGBAYAN', 'local_church'=> 'Binan', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPBI00027', 'name'=>'KIM NAVORRA', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00095', 'name'=>'MARIA LOURDES ELOMINA', 'local_church'=> 'Canlubang', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPDA00010', 'name'=>'SHARMANE PENSOL', 'local_church'=> 'Dasmarinas', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPIS00015', 'name'=>'GLORIE ANN UY', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPIS00010', 'name'=>'JOANA CATCHAN', 'local_church'=> 'Isabela', 'day_1'=>'N', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPMU00016', 'name'=>'AIZELLE BERNARDO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00158', 'name'=>'MAEGAN MALAYAO', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00195', 'name'=>'GABRIEL JAMES MEIJA', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00071', 'name'=>'KAREN ALVAREZ', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00022', 'name'=>'CHRISTINE CABANTOG', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00077', 'name'=>'VICTORIE CABERO', 'local_church'=> 'Muntinlupa', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'N', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00133', 'name'=>'KAZANDRA VALENTIN', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00012', 'name'=>'APRIL JOY BALANE', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPPA00044', 'name'=>'MA. JERRIPER OVIEDO', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'N'],
            ['uuid'=>'LPTA00004', 'name'=>'MARK DALE MARTIZANO', 'local_church'=> 'Tarlac', 'day_1'=>'N', 'day_2' => 'N', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00086', 'name'=>'MIKEE SIMON', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPPA00022', 'name'=>'REY CAMACHO', 'local_church'=> 'Pateros', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPTA00028', 'name'=>'JOSHUA ALCIBAR', 'local_church'=> 'Tarlac', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00160', 'name'=>'ALFRED MORCILLO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPBI00109', 'name'=>'PAULO JUAREZ', 'local_church'=> 'Binan', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00171', 'name'=>'DARWIN BIROT', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPCA00125', 'name'=>'JOMARI OLIVER', 'local_church'=> 'Canlubang', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00149', 'name'=>'ANGELICA DAPITAN', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00094', 'name'=>'JONNA SALUMBIDES', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00017', 'name'=>'EDSON BERNARDO', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00052', 'name'=>'STEPHANY EVANGELISTA', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00081', 'name'=>'KELVI PASCUAL', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y'],
            ['uuid'=>'LPMU00051', 'name'=>'PIA EVANGELISTA', 'local_church'=> 'Muntinlupa', 'day_1'=>'Y', 'day_2' => 'Y', 'day_3'=>'Y', 'day_4' => 'Y']
        );

        foreach ($bookMe as $data) {
            $this->command->info('---------------- booking volunteers ---------------');
            
            Booking::where('registration_uuid', $data['uuid'])->delete();

            $registration = Registration::where('uuid', $data['uuid'])->first();

            if ($registration) {
                $registration->update(['attending_option' => 'Hybrid', 'can_book' => true, 'is_booking_bypassed' => false]);
            }

            $this->command->info('AWTA Card #: ' . $data['uuid'] . ' Full Name: ' . $data['name']);

            $dateToBeBooked = [];
            $booked_log = 'Booked Day(s): ';
            for ($x = 1; $x <= 4; $x++) {
                if ($data['day_' . $x] === 'Y') {
                    $booked_log .= 'Day ' . $x . ' ';
                    array_push($dateToBeBooked, [
                        'registration_uuid' => $data['uuid'],
                        'slot_id' => $x,
                        'local_church' => $data['local_church']
                    ]);
                }
            }

            Booking::insert($dateToBeBooked);

            $this->command->info('Booked Day(s): ' . $booked_log);
            $this->command->info('------------------------------ done -----------------------------');
        }
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
