<?php

namespace Database\Seeders;

use App\Models\Registration;
use Illuminate\Database\Seeder;

class BypassRegistrationBooking extends Seeder
{
    public function run()
    {
        $bypassedDelegates = [
            ['uuid' => 'LPMU00272', 'name' => 'JAKE IMPERIAL'],
            ['uuid' => 'LPBI00039', 'name' => 'KEY ANN GARCIA'],
            ['uuid' => 'LPMU00111', 'name' => 'BRYAN SANTA ROSA'],
            ['uuid' => 'LPBI00017', 'name' => 'JOHN MICHAEL ROBLES'],
            ['uuid' => 'LPMU00031', 'name' => 'KLAUD LAUREANO'],
            ['uuid' => 'LPMU00061', 'name' => 'MICHAEL LAUREANO'],
            ['uuid' => 'LPMU00064', 'name' => 'GAUDENCIO LIGAMEN III'],
            ['uuid' => 'LPMU00008', 'name' => 'MICHAEL ARELLANO'],
            ['uuid' => 'LPMU00432', 'name' => 'JAZREAL BALANAY'],
            ['uuid' => 'LPCA00327', 'name' => 'NOEL BUQUID'],
            ['uuid' => 'LPBI00125', 'name' => 'DEXTER CONCEPCION'],
            ['uuid' => 'LPMU00263', 'name' => 'ADAM GUNA'],
            ['uuid' => 'LPMU00188', 'name' => 'DARYL GUTIERREZ'],
            ['uuid' => 'LPMU00284', 'name' => 'JAMES JAGAPE'],
            ['uuid' => 'LPMU00299', 'name' => 'ANGELO LAGRIADA'],
            ['uuid' => 'LPMU00343', 'name' => 'HIRO MORALES'],
            ['uuid' => 'LPMU00209', 'name' => 'MARK DANIEL REMUGAT'],
            ['uuid' => 'LPMU00071', 'name' => 'JUMAR TOLEDO'],
            ['uuid' => 'LPBI00025', 'name' => 'IAN RODRIGUEZ'],
            ['uuid' => 'LPBI00064', 'name' => 'JESON GARCIA'],
            ['uuid' => 'LPMU00323', 'name' => 'PAULENE BALISI'],
            ['uuid' => 'LPMU00014', 'name' => 'RHEAN BASBANIO'],
            ['uuid' => 'LPMU00308', 'name' => 'MARK JOY BAYLON'],
            ['uuid' => 'LPMU00205', 'name' => 'AGATHA PAJENADO'],
            ['uuid' => 'LPMU00259', 'name' => 'ERICKA VELASCO'],
            ['uuid' => 'LPMU00268', 'name' => 'JIA VINLUAN'],
            ['uuid' => 'LPMU00032', 'name' => 'KIM IMPERIAL'],
            ['uuid' => 'LPMU00058', 'name' => 'MJ HERNANDEZ'],
            ['uuid' => 'LPMU00230', 'name' => 'KARL LORENZ TUD'],
            ['uuid' => 'LPBI00012', 'name' => 'JUDIE LABRADOR'],
            ['uuid' => 'LPBI00081', 'name' => 'WENDY AGUINALDO'],
            ['uuid' => 'LPBI00124', 'name' => 'DREXLER CONCEPCION'],
            ['uuid' => 'LPMU00143', 'name' => 'JEANINE BELANE'],
            ['uuid' => 'LPMU00069', 'name' => 'TOBY MADRID'],
            ['uuid' => 'LPMU00031', 'name' => 'KLAUD LAUREANO'],
            ['uuid' => 'LPMU00038', 'name' => 'NIL DE VERA'],
            ['uuid' => 'LPMU00092', 'name' => 'ROXANNE ADEVARUFO'],
            ['uuid' => 'LPMU00244', 'name' => 'KAREN TAN'],
            ['uuid' => 'LPPA00001', 'name' => 'AMOR ABAD'],
            ['uuid' => 'LPVA00007', 'name' => 'JAMIE BIROT'],
            ['uuid' => 'LPMU00041', 'name' => 'JULIE PEARL DIAZ'],
            ['uuid' => 'LPTA00030', 'name' => 'KARISSA MELCHOR'],
            ['uuid' => 'LPTA00040', 'name' => 'JOEMARIE TAGALOG'],
            ['uuid' => 'LPTA00070', 'name' => 'JENNILYN MARIN'],
            ['uuid' => 'LPTA00010', 'name' => 'MARICEL TUD'],
            ['uuid' => 'LPBI00029', 'name' => 'MYRNA GARCIA'],
            ['uuid' => 'LPBI00101', 'name' => 'RACHEL ANN GARCIA'],
            ['uuid' => 'LPBI00033', 'name' => 'AMY JOSE'],
            ['uuid' => 'LPBI00007', 'name' => 'BEVERLY DELA CRUZ'],
            ['uuid' => 'LPBI00009', 'name' => 'KATRINA PARAYNO'],
            ['uuid' => 'LPBI00020', 'name' => 'JULIE CELLO'],
            ['uuid' => 'LPBI00142', 'name' => 'JENICA CELLO'],
            ['uuid' => 'LPBI00003', 'name' => 'ANDY CELLO'],
            ['uuid' => 'LPBI00057', 'name' => 'DARIUSE ANDINO'],
            ['uuid' => 'LPBI00024', 'name' => 'ELIX ANDINO'],
            ['uuid' => 'LPBI00125', 'name' => 'DEXTER CONCEPTION'],
            ['uuid' => 'LPPA00067', 'name' => 'ANGIE CAMACHO'],
            ['uuid' => 'LPPA00070', 'name' => 'PINKY MALBAS'],
            ['uuid' => 'LPPA00075', 'name' => 'JAVIER SANCHEZ'],
            ['uuid' => 'LPPA00066', 'name' => 'KENJIE BUENAVENTURA'],
            ['uuid' => 'LPPA00072', 'name' => 'ANDY ESCOTOTO'],
            ['uuid' => 'LPCA00077', 'name' => 'MARIE AMOLAR'],
            ['uuid' => 'LPCA00154', 'name' => 'DELY AALA'],
            ['uuid' => 'LPCA00166', 'name' => 'AMY AMLOG'],
            ['uuid' => 'LPCA00230', 'name' => 'DORCAS URGELLES'],
            ['uuid' => 'LPCA00099', 'name' => 'PRINCESS EVASCO'],
            ['uuid' => 'LPCA00023', 'name' => 'ANGEL MARTINEZ'],
            ['uuid' => 'LPCA00047', 'name' => 'EVANGELINE PUMANES'],
            ['uuid' => 'LPCA00124', 'name' => 'JENNY OLIVER'],
            ['uuid' => 'LPCA00021', 'name' => 'RODGIE PORTES'],
            ['uuid' => 'LPCA00008', 'name' => 'BHELLA HIDALGO'],
            ['uuid' => 'LPMU00024', 'name' => 'ANNA VERONICA CHUA'],
            ['uuid' => 'LPMU00079', 'name' => 'JERUM OROBIA'],
            ['uuid' => 'LPMU00010', 'name' => 'LANIE ATIENZA'],
            ['uuid' => 'LPMU00072', 'name' => 'JOYCE MALAYAO'],
            ['uuid' => 'LPMU00164', 'name' => 'BING SANTILLAN'],
            ['uuid' => 'LPMU00136', 'name' => 'MARU VILLAFLOR'],
            ['uuid' => 'LPBI00106', 'name' => 'KATE GARCIA'],
            ['uuid' => 'LPBI00034', 'name' => 'CAMILLE ALMEIDA'],
            ['uuid' => 'LPPA00007', 'name' => 'JEAN BAUTISTA'],
            ['uuid' => 'LPPA00060', 'name' => 'ARLO VALDELLON'],
            ['uuid' => 'LPMU00391', 'name' => 'JEN LAGORRA'],
            ['uuid' => 'LPMU00392', 'name' => 'RACHEL MAE HIDALGO'],
            ['uuid' => 'LPBI00013', 'name' => 'MICAELLA RODEL'],
            ['uuid' => 'LPBI00124', 'name' => 'ROXANNE ADEVARUFO'],
            ['uuid' => 'LPMU00244', 'name' => 'KENG TAN'],
            ['uuid' => 'LPMU00071', 'name' => 'JAM TOLEDO'],
            ['uuid' => 'LPMU00299', 'name' => 'ANGELO LAGRIADA'],
            ['uuid' => 'LPMU00139', 'name' => 'DAN RAMOS'],
            ['uuid' => 'LPMU00079', 'name' => 'JERUM OROBIA'],
            ['uuid' => 'LPMU00085', 'name' => 'YUAN REALUYO'],
            ['uuid' => 'LPMU00209', 'name' => 'DANIEL REMUGAT'],
            ['uuid' => 'LPMU00188', 'name' => 'JHIRO DELOS SANTOS'],
            ['uuid' => 'LPMU00201', 'name' => 'VIC LORENZ NUÑEZ'],
            ['uuid' => 'LPMU00284', 'name' => 'JAMES JAGAPE'],
            ['uuid' => 'LPMU00111', 'name' => 'BRYAN STA. ROSA'],
            ['uuid' => 'LPMU00032', 'name' => 'KIM SHEENA CUASAY IMPERIAL'],
            ['uuid' => 'LPMU00230', 'name' => 'KARL LORENZ TUD'],
            ['uuid' => 'LPMU00061', 'name' => 'MICHAEL LAUREANO'],
            ['uuid' => 'LPMU00031', 'name' => 'KLAUD LAUREANO'],
            ['uuid' => 'LPMU00069', 'name' => 'SETH TOBIAS MADRID'],
            ['uuid' => 'LPMU00058', 'name' => 'MARK JAMES HERNANDEZ'],
            ['uuid' => 'LPMU00041', 'name' => 'JULIE PEARL DIAZ'],
            ['uuid' => 'LPMU00115', 'name' => 'AERON JUDE TANAEL'],
            ['uuid' => 'LPMU00168', 'name' => 'NICOLE ANDALES'],
            ['uuid' => 'LPMU00109', 'name' => 'MARIA BERNADETTE SOMEROS'],
            ['uuid' => 'LPMU00092', 'name' => 'KEVIN BIROT'],
            ['uuid' => 'LPMU00092', 'name' => 'TEL JOSE'],
            ['uuid' => 'LPMU00092', 'name' => 'FERNAN CAPITO'],
            ['uuid' => 'LPMU00092', 'name' => 'ABRAM FRIANEZA'],
            ['uuid' => 'LPMU00092', 'name' => 'MARJ FRIANEZA'],
            ['uuid' => 'LPMU00398', 'name' => 'VIRGINIA MARI (BERJ) BATITIS'],
            ['uuid' => 'LPBI00010', 'name' => 'ALEXANDER CELLO'],
            ['uuid' => 'LPMU00030', 'name' => 'LINDA VALENTIN'],
            ['uuid' => 'LPBI00004', 'name' => 'DHAZLE DE VERA'],
            ['uuid' => 'LPBI00084', 'name' => 'ROSE DALAWANGBAYAN'],
            ['uuid' => 'LPBI00027', 'name' => 'KIM NAVORRA'],
            ['uuid' => 'LPCA00095', 'name' => 'MARIA LOURDES ELOMINA'],
            ['uuid' => 'LPDA00010', 'name' => 'SHARMANE PENSOL'],
            ['uuid' => 'LPDA00007', 'name' => 'MAILA GOMEZ'],
            ['uuid' => 'LPIS00015', 'name' => 'GLORIE ANN UY'],
            ['uuid' => 'LPIS00010', 'name' => 'JOANA CATCHAN'],
            ['uuid' => 'LPMU00016', 'name' => 'AIZELLE BERNARDO'],
            ['uuid' => 'LPMU00158', 'name' => 'MAEGAN MALAYAO'],
            ['uuid' => 'LPMU00195', 'name' => 'GABRIEL JAMES MEIJA'],
            ['uuid' => 'LPCA00071', 'name' => 'KAREN MELGAZO'],
            ['uuid' => 'LPCA00059', 'name' => 'ALMA TIAMSING'],
            ['uuid' => 'LPMU00022', 'name' => 'CHRISTINE CABANTOG'],
            ['uuid' => 'LPMU00077', 'name' => 'VICTORIE CABERO'],
            ['uuid' => 'LPMU00133', 'name' => 'KAZANDRA VALENTIN'],
            ['uuid' => 'LPMU00012', 'name' => 'APRIL JOY BALANE'],
            ['uuid' => 'LPPA00044', 'name' => 'MA. JERRIPER OVIEDO'],
            ['uuid' => 'LPTA00004', 'name' => 'MARK DALE MARTIZANO'],
            ['uuid' => 'LPVA00005', 'name' => 'YHIN MENESES'],
            ['uuid' => 'LPVA00004', 'name' => 'JIVVI DE VERA'],
            ['uuid' => 'LPVA00004', 'name' => 'NIL DE VERA'],
            ['uuid' => 'LPMU00038', 'name' => 'TIN TUD'],
            ['uuid' => 'LPMU00129', 'name' => 'CARLO BALLESTEROS'],
            ['uuid' => 'LPCA00080', 'name' => 'JAZZ MELLA'],
            ['uuid' => 'LPCA00225', 'name' => 'JOCHELLE GUTIERREZ'],
            ['uuid' => 'LPCA00225', 'name' => 'JONATHAN PUMANES'],
            ['uuid' => 'LPBI00022', 'name' => 'CRIS ANN JOSE'],
            ['uuid' => 'LPMU00199', 'name' => 'MELANIE NGITNGIT'],
            ['uuid' => 'LPBI00086', 'name' => 'MIKEE SIMON'],
            ['uuid' => 'LPPA00022', 'name' => 'REY CAMACHO'],
            ['uuid' => 'LPTA00028', 'name' => 'JOSHUA ALCIBAR'],
            ['uuid' => 'LPMU00160', 'name' => 'ALFRED MORCILLO'],
            ['uuid' => 'LPBI00109', 'name' => 'PAULO JUAREZ'],
            ['uuid' => 'LPMU00171', 'name' => 'DARWIN BIROT'],
            ['uuid' => 'LPMU00355', 'name' => 'MARK GALVAN'],
            ['uuid' => 'LPCA00125', 'name' => 'JOMARI OLIVER'],
            ['uuid' => 'LPMU00149', 'name' => 'ANGELICA DAPITAN'],
            ['uuid' => 'LPBI00105', 'name' => 'KEVIN BIROT'],
            ['uuid' => 'LPMU00061', 'name' => 'MICHAEL LAUREANO'],
            ['uuid' => 'LPMU00094', 'name' => 'JONNA SALUMBIDES'],
            ['uuid' => 'LPMU00017', 'name' => 'EDSON BERNARDO'],
            ['uuid' => 'LPMU00016', 'name' => 'AIZELLE BERNARDO'],
            ['uuid' => 'LPMUN0052', 'name' => 'STEPHANY EVANGELISTA'],
            ['uuid' => 'LPMU00081', 'name' => 'KELVI PASCUAL'],
            ['uuid' => 'LPMU00051', 'name' => 'PIA EVANGELISTA'],
            ['uuid' => 'LPMU00199', 'name' => 'MELANIE NGITNGIT'],
            ['uuid' => 'LPMU00038', 'name' => 'NIL DE VERA'],
            ['uuid' => 'LPMU00195', 'name' => 'JAMES MEJIA'],
            ['uuid' => 'LPMU00061', 'name' => 'MICHAEL LAUREANO'],
            ['uuid' => 'LPMU00002', 'name' => 'ELVIRA DELA CRUZ'],
            ['uuid' => 'LPMU00213', 'name' => 'ARLENE SUNGA'],
            ['uuid' => 'LPMU00150', 'name' => 'BONG DELA CRUZ'],
            ['uuid' => 'LPMU00176', 'name' => 'CLAUSELYN CUASAY'],
            ['uuid' => 'LPMU00103', 'name' => 'MICHELLE SHROCK'],
            ['uuid' => 'LPMU00051', 'name' => 'PIA EVANGELISTA'],
            ['uuid' => 'LPMU00274', 'name' => 'TIMOTHY PADERNAL'],
            ['uuid' => 'LPMU00066', 'name' => 'KATE LOPEZ'],
            ['uuid' => 'LPMU00196', 'name' => 'JAYKA MIRASOL'],
            ['uuid' => 'LPMU00043', 'name' => 'GRACE DIO'],
            ['uuid' => 'LPMU00093', 'name' => 'MICHAEL SALUMBIDES'],
            ['uuid' => 'LPMU00042', 'name' => 'DEXTER DIO'],
            ['uuid' => 'LPBI00040', 'name' => 'ALDEN GARCIA'],
            ['uuid' => 'LPMU00003', 'name' => 'ALMA TIAMSING'],
            ['uuid' => 'LPMU00070', 'name' => 'ANGEL ENDRIGA'],
            ['uuid' => 'LPMU00168', 'name' => 'ARABELLE PEÑAREDONDA-PUMANES'],
            ['uuid' => 'LPCA00101', 'name' => 'INAH JEUNE'],
            ['uuid' => 'LPCA00031', 'name' => 'JANISSE MELLA'],
            ['uuid' => 'LPMU00189', 'name' => 'JAZZ MELLA'],
            ['uuid' => 'LPCA00225', 'name' => 'JOCHELLE GUTIERREZ'],
            ['uuid' => 'LPMU00168', 'name' => 'NICOLE ANDALES'],
            ['uuid' => 'LPMU00392', 'name' => 'RACHEL MAE HIDALGO'],
            ['uuid' => 'LPMU00003', 'name' => 'RACQUEL ADLONG'],
            ['uuid' => 'LPMU00070', 'name' => 'SHAILA GAIN MADRID'],
            ['uuid' => 'LPMU00201', 'name' => 'VIC LORENZ NUÑEZ'],

            ['uuid'=>'LPBI00132', 'name'=>'Joselito Birot'],
            ['uuid'=>'LPBI00019', 'name'=>'Elvira Birot'],
            ['uuid'=>'LPBI00010', 'name'=>'Alexander Cello'],
            ['uuid'=>'LPBI00142', 'name'=>'Jenica Cello'],
            ['uuid'=>'LPBI00107', 'name'=>'Ernesto Garcia'],
            ['uuid'=>'LPBI00029', 'name'=>'Myrna Garcia'],
            ['uuid'=>'LPVA00015', 'name'=>'Gina Dolz'],
            ['uuid'=>'LPIS00009', 'name'=>'Marloun Aala'],
            ['uuid'=>'LPCA00116', 'name'=>'Agnes Aala'],
            ['uuid'=>'LPTA00011', 'name'=>'Jose Dante Tud'],
            ['uuid'=>'LPTA00010', 'name'=>'Maricel  Tud'],
            ['uuid'=>'LPPA00021', 'name'=>'Marilou Camacho'],
            ['uuid'=>'LPPA00022', 'name'=>'Reynaldo Camacho'],
            ['uuid'=>'LPPA00070', 'name'=>'Jocelyn Malbas'],
            ['uuid'=>'LPPA00071', 'name'=>'Fidel Malbas'],
            ['uuid'=>'LPMU00001', 'name'=>'Isaias Jr. Dela Cruz'],
            ['uuid'=>'LPMU00002', 'name'=>'Elvie Dela Cruz'],
            ['uuid'=>'LPMU00105', 'name'=>'Paulo Sison'],
            ['uuid'=>'LPMU00106', 'name'=>'Ma. Criselda Sison'],
            ['uuid'=>'LPMU00107', 'name'=>'Apolinario Someros'],
            ['uuid'=>'LPMU00253', 'name'=>'Riza Someros'],
            ['uuid'=>'LPMU00050', 'name'=>'Pio Evangelista'],
            ['uuid'=>'LPMU00121', 'name'=>'Joselito Tud'],
            ['uuid'=>'LPMU00122', 'name'=>'Amelia Tud'],
            ['uuid'=>'LPMU00067', 'name'=>'Gary Madrid'],
            ['uuid'=>'LPMU00068', 'name'=>'Divine Madrid'],
            ['uuid'=>'LPCA00001', 'name'=>'Julio Mella'],
            ['uuid'=>'LPCA00002', 'name'=>'Jennifer Mella'],
            ['uuid'=>'LPCA00046', 'name'=>'Ronald Czerny Pumanes'],
            ['uuid'=>'LPCA00047', 'name'=>'Evangelina Pumanes'],
            ['uuid'=>'LPCA00202', 'name'=>'Larry Silva'],
            ['uuid'=>'LPCA00201', 'name'=>'Alma Silva'],
            ['uuid'=>'LPCA00026', 'name'=>'Roger Martinez'],
            ['uuid'=>'LPCA00023', 'name'=>'Angeles Martinez'],
            ['uuid'=>'LPCA00040', 'name'=>'Orsos Gerald'],
            ['uuid'=>'LPCA00039', 'name'=>'Orsos Mia'],
            ['uuid'=>'LPCA00123', 'name'=>'Oliver Orlando'],
            ['uuid'=>'LPCA00124', 'name'=>'Oliver Jennifer'],
            ['uuid'=>'LPDA00006', 'name'=>'Jerome Velasco'],
            ['uuid'=>'LPDA00032', 'name'=>'Michelle Velasco'],
            ['uuid'=>'LPDA00002', 'name'=>'Piolo Jirah Tuliao'],
            ['uuid'=>'LPDA00001', 'name'=>'Eddie Tuliao'],
        ];

        foreach ($bypassedDelegates as $delegate) {
            $registration = Registration::where('uuid', $delegate['uuid'])->first();

            if ($registration) {
                $registration->is_booking_bypassed = true;
                $registration->save();
            }
        }
    }
}
