<?php

namespace Database\Seeders;

use App\Models\LookUp;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class LookUpTableSeeder2 extends Seeder
{
    public function run()
    {
        $array = [
            ['lamp_card_number' => 'LPBI00215', 'email' => 'polinpanaligan@gmail.com', 'firstname' => 'Pauline', 'lastname' => 'Panaligan', 'facebook_name' => 'Pauline Panaligan', 'registration_type' => 'Member', 'local_church' => 'Binan', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00434', 'email' => 'Ruffamayloriega@gmail.com', 'firstname' => 'Ruffa May', 'lastname' => 'Loriega', 'facebook_name' => 'Ruffa May Loriega', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00130', 'email' => 'alfredtiamzon5@gmail.com', 'firstname' => 'Neil Victor', 'lastname' => 'Distrito', 'facebook_name' => 'Neil Distrito', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00137', 'email' => 'crystlg0018@gmail.com', 'firstname' => 'Niño Vin', 'lastname' => 'Laquindanum', 'facebook_name' => 'Niño Laquindanum', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00139', 'email' => 'ninadelacruz262003@gmail.com', 'firstname' => 'Nina', 'lastname' => 'Dela Cruz', 'facebook_name' => 'Nina Dela Cruz', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00140', 'email' => 'aezelgutierrez@gmail.com', 'firstname' => 'Ethan James', 'lastname' => 'Pasion', 'facebook_name' => 'Ethan Pasion', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00143', 'email' => 'aezelgutierrez@gmail.com', 'firstname' => 'Judy Ann', 'lastname' => 'Marin', 'facebook_name' => 'Judy Ann Marin', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00144', 'email' => 'aezelgutierrez@gmail.com', 'firstname' => 'Errol', 'lastname' => 'Marin', 'facebook_name' => 'Errol Marin', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00145', 'email' => 'aezelgutierrez@gmail.com', 'firstname' => 'PAULA', 'lastname' => 'SOTTO', 'facebook_name' => 'Paula Sotto', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00146', 'email' => 'aezelgutierrez@gmail.com', 'firstname' => 'Aristotle', 'lastname' => 'Sicat', 'facebook_name' => 'Aris Sicat', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00150', 'email' => 'aezelgutierrez@gmail.com', 'firstname' => 'Nicole', 'lastname' => 'Garcia', 'facebook_name' => 'Nicole Garcia', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00453', 'email' => 'ajnapostol@gmail.com', 'firstname' => 'Aida', 'lastname' => 'Apostol', 'facebook_name' => 'Aidajoyapostol', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00454', 'email' => 'ajnapostol@gmail.com', 'firstname' => 'Asher  Jethro', 'lastname' => 'Apostol', 'facebook_name' => 'Asher Jethro N. Apostol', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00152', 'email' => 'michaelcasupanan20@gmail.com', 'firstname' => 'Shaira shane', 'lastname' => 'Bautista', 'facebook_name' => 'Shaira shane', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00460', 'email' => 'Micoodascojulyo1@gmail.com', 'firstname' => 'Mico', 'lastname' => 'Odasco', 'facebook_name' => 'Mico Odasco', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPDA00138', 'email' => 'maryannellis99@gmail.com', 'firstname' => 'Mary ann', 'lastname' => 'Ellis', 'facebook_name' => 'Mary ann ellis', 'registration_type' => 'Member', 'local_church' => 'Dasmarinas', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPBI00222', 'email' => 'Menchiegalvez397@gmail.com', 'firstname' => 'Herminia', 'lastname' => 'Galvez', 'facebook_name' => 'Menchie Galvez', 'registration_type' => 'Member', 'local_church' => 'Binan', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPBI00223', 'email' => 'Menchiegalvez397@gmail.com', 'firstname' => 'Rachel Claire', 'lastname' => 'Galvez', 'facebook_name' => 'Claire Rachel', 'registration_type' => 'Member', 'local_church' => 'Binan', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPBI00224', 'email' => 'Menchiegalvez397@gmail.com', 'firstname' => 'Raizy May', 'lastname' => 'Galvez', 'facebook_name' => 'Raizy May Galvez', 'registration_type' => 'Member', 'local_church' => 'Binan', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPDA00139', 'email' => 'Joycauton18@gmail.com', 'firstname' => 'Mark joshua', 'lastname' => 'Cauton', 'facebook_name' => 'Mark joshua Cauton', 'registration_type' => 'Member', 'local_church' => 'Dasmarinas', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPDA00140', 'email' => 'Joycauton18@gmail.com', 'firstname' => 'James Andrew', 'lastname' => 'Cauton', 'facebook_name' => '', 'registration_type' => 'Member', 'local_church' => 'Dasmarinas', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00506', 'email' => 'czai_0407@yahoo.com', 'firstname' => 'Ana Maria', 'lastname' => 'de Luna', 'facebook_name' => 'Arianne De Luna', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPMU00583', 'email' => 'diazmiccaela@gmail.con', 'firstname' => 'Miccaela', 'lastname' => 'Diaz', 'facebook_name' => 'Miccaela Diaz', 'registration_type' => 'Member', 'local_church' => 'Muntinlupa', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00159', 'email' => 'crystlg0018@gmail.com', 'firstname' => 'Nicolas', 'lastname' => 'Gozum', 'facebook_name' => 'Nicolas Gozum', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPBI00231', 'email' => 'Dhazle03@gmail.com', 'firstname' => 'Joshua', 'lastname' => 'De Vera', 'facebook_name' => 'Joshua de Vera', 'registration_type' => 'Member', 'local_church' => 'Binan', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPDA00145', 'email' => 'sha.pensol@gmail.com', 'firstname' => 'Dareem Jost', 'lastname' => 'Tolentino', 'facebook_name' => 'Dareem Jost Tolentino', 'registration_type' => 'Member', 'local_church' => 'Dasmarinas', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPDA00146', 'email' => 'sha.pensol@gmail.com', 'firstname' => 'Juanito', 'lastname' => 'Esponilla', 'facebook_name' => 'Reyse May', 'registration_type' => 'Member', 'local_church' => 'Dasmarinas', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00515', 'email' => 'Lovelyjoybancale17@gmail.com', 'firstname' => 'Lovely Joy', 'lastname' => 'Bancale', 'facebook_name' => 'Lovely Bancale', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00173', 'email' => 'crystlg0018@gmail.com', 'firstname' => 'Rachelle', 'lastname' => 'Lopez', 'facebook_name' => 'Rachelle Lopez', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00174', 'email' => 'lu.johrobertt.3098@gmail.com', 'firstname' => 'Jobs', 'lastname' => 'Lu', 'facebook_name' => 'J price Lucio', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00175', 'email' => '', 'firstname' => 'Cherry Lou', 'lastname' => 'Lu', 'facebook_name' => 'Lu Cass', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00532', 'email' => 'vergaramaricar90@gmail.com', 'firstname' => 'Maricar', 'lastname' => 'Vergara', 'facebook_name' => 'Maricar Vergara', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00533', 'email' => 'jennelyntupig.bended@gmail.com', 'firstname' => 'JENNELYN', 'lastname' => 'TUPIG', 'facebook_name' => 'Jennelyn Tupig Solo', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00534', 'email' => '', 'firstname' => 'JENNECA', 'lastname' => 'SOLO', 'facebook_name' => '', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPMU00586', 'email' => 'meriolespl@gmail.com', 'firstname' => 'Kyle Darvinne', 'lastname' => 'Pajanostan', 'facebook_name' => 'Darvinne kyle Pajanostan', 'registration_type' => 'Member', 'local_church' => 'Muntinlupa', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPPA00113', 'email' => 'claresantos07@yahoo.com', 'firstname' => 'Clare', 'lastname' => 'Santos', 'facebook_name' => 'Clare Santos', 'registration_type' => 'Member', 'local_church' => 'Pateros', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPPA00114', 'email' => 'elvinamheann@gmail.com', 'firstname' => 'Mary Ann', 'lastname' => 'Elvina', 'facebook_name' => 'Mhean Elvina', 'registration_type' => 'Member', 'local_church' => 'Pateros', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00562', 'email' => 'heramargigiabsalon@gmail.com', 'firstname' => 'Heramar Gigi', 'lastname' => 'Absalon', 'facebook_name' => 'Heramar Gigi Absalon', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPPA00116', 'email' => 'cela09074764193@gmail.com', 'firstname' => 'Marcela', 'lastname' => 'Barnachea', 'facebook_name' => 'Marcela Barnachea', 'registration_type' => 'Member', 'local_church' => 'Pateros', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPPA00118', 'email' => 'hylene77@gmail.com', 'firstname' => 'John Hydrian', 'lastname' => 'De Una', 'facebook_name' => 'John Hydrian De Una', 'registration_type' => 'Member', 'local_church' => 'Pateros', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPPA00119', 'email' => 'barnacheajessa11@gmail.com', 'firstname' => 'Jessa', 'lastname' => 'Barnachea', 'facebook_name' => 'Barnachea Villa Jessa', 'registration_type' => 'Member', 'local_church' => 'Pateros', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00176', 'email' => 'maritonigopezcabarliza@gmail.com', 'firstname' => 'Maritoni', 'lastname' => 'Cabarliza', 'facebook_name' => 'Maritoni Gopez Cabarliza', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00563', 'email' => 'charbigantalao@gmail.com', 'firstname' => 'gantalao', 'lastname' => 'catherine', 'facebook_name' => 'catherine gantalao', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPDA00164', 'email' => 'anjfernandez1106@yahoo.com', 'firstname' => 'Marcelino', 'lastname' => 'Magno', 'facebook_name' => 'Marcelino Magno', 'registration_type' => 'Member', 'local_church' => 'Dasmarinas', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00597', 'email' => 'rosearciaga7@gmail.com', 'firstname' => 'Juvilyn', 'lastname' => 'Mabolo', 'facebook_name' => 'Juvilyn Mabolo', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00702', 'email' => 'delarosajanesarah@gmail.com', 'firstname' => 'Sarah Jane', 'lastname' => 'Dela Rosa', 'facebook_name' => 'Sarah Dela Rosa', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPPA00139', 'email' => '', 'firstname' => 'Erica Mae', 'lastname' => 'Estores', 'facebook_name' => 'Erica Mae Estores', 'registration_type' => 'Member', 'local_church' => 'Pateros', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00714', 'email' => 'micahjoymanguino5@gmail.com', 'firstname' => 'Joan', 'lastname' => 'Ingles', 'facebook_name' => 'France Nicole', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPPA00140', 'email' => '', 'firstname' => 'Analisa', 'lastname' => 'Paelmo', 'facebook_name' => 'Liezel Paelmo', 'registration_type' => 'Member', 'local_church' => 'Pateros', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPDC00175', 'email' => 'monica_allera@yahoo.com.ph', 'firstname' => 'Angie', 'lastname' => 'Pansacala', 'facebook_name' => 'Angie Distrito', 'registration_type' => 'Member', 'local_church' => 'DC Cruz', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPDC00176', 'email' => 'monica_allera@yahoo.com.ph', 'firstname' => 'Alfred', 'lastname' => 'Pansacala', 'facebook_name' => 'Angie Distrito', 'registration_type' => 'Member', 'local_church' => 'DC Cruz', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPDC00177', 'email' => 'monica_allera@yahoo.com.ph', 'firstname' => 'Mathew', 'lastname' => 'Pansacala', 'facebook_name' => 'Angie Pansacala', 'registration_type' => 'Member', 'local_church' => 'DC Cruz', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPTA00177', 'email' => '', 'firstname' => 'John bryan son', 'lastname' => 'Balingit', 'facebook_name' => 'John bryanson balingit', 'registration_type' => 'Member', 'local_church' => 'Tarlac', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPPA00141', 'email' => 'bondoccharice041@gmail.com', 'firstname' => 'Charice', 'lastname' => 'Bondoc', 'facebook_name' => 'Charice Bondoc', 'registration_type' => 'Member', 'local_church' => 'Pateros', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPCA00772', 'email' => 'manguinomina10@gmail.com', 'firstname' => 'Jazley', 'lastname' => 'Manguino', 'facebook_name' => 'Mina Manguino', 'registration_type' => 'Member', 'local_church' => 'Canlubang', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPMU00602', 'email' => 'maritesscustodio@yahoo.com', 'firstname' => 'Rodolfo', 'lastname' => 'Custodio', 'facebook_name' => 'Rudolfo custodio jr', 'registration_type' => 'Member', 'local_church' => 'Muntinlupa', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
            ['lamp_card_number' => 'LPMU00606', 'email' => '', 'firstname' => 'Rheynarose', 'lastname' => 'Mangulabnan', 'facebook_name' => '', 'registration_type' => 'Member', 'local_church' => 'Muntinlupa', 'country' => 'Philippines', 'category' => 'Adult', 'can_book_days' => '2'],
        ];

        $this->command->info(count($array));

        for ($i = 0; $i <= count($array) - 1; $i++) {
            $this->command->info(json_encode($array[$i]['lamp_card_number']));
            $lookup = LookUp::create([
                'lamp_card_number' => $array[$i]['lamp_card_number'],
                'email' => $array[$i]['email'],
                'firstname' => $array[$i]['firstname'],
                'lastname' => $array[$i]['lastname'],
                'fullname' => $array[$i]['firstname'] . ' ' . $array[$i]['lastname'],
                'facebook_name' => $array[$i]['facebook_name'],
                'registration_type' => $array[$i]['registration_type'],
                'category' => $array[$i]['category'],
                'local_church' => $array[$i]['local_church'],
                'country' => $array[$i]['country'],
                'can_book_days' => $array[$i]['can_book_days']
            ]);
        }
    }
}
