<?php

namespace Database\Seeders;

use App\Enums\AttendingOption;
use App\Models\LookUp;
use App\Models\Registration;
use Illuminate\Database\Seeder;

class RegLoggerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['lamp_card_number' => 'LPDC00001', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00003', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00004', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00005', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00006', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00007', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00008', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00009', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00010', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00011', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00012', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00013', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00014', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00015', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00016', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00017', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00018', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00019', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00020', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00021', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00022', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00023', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00024', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00025', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00026', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00027', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00028', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00029', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00030', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00031', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00032', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00034', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00035', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00036', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00037', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00038', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00039', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00040', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00041', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00042', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00043', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00044', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00045', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00046', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00047', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00048', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00049', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00050', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00051', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00052', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00053', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00054', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00055', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00056', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00057', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00058', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00059', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00060', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00061', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00062', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00063', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00064', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00065', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00066', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00067', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPDC00068', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPDC00069', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00070', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00071', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00073', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00074', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00075', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00076', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00077', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00078', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00079', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00080', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00081', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00082', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00083', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00084', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00085', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00086', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00087', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00088', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00089', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00090', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00091', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00092', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00093', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00094', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00095', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00096', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00097', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00098', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00099', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00100', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00101', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00102', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00103', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00104', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPDC00105', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPDC00106', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00107', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00136', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00137', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00138', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00139', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00140', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00141', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00142', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00143', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00144', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00145', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00146', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00147', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00148', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00149', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00150', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00151', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00152', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00153', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00154', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00155', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00156', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00157', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00158', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00159', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00160', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00161', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00162', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00163', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00164', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00165', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00166', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00167', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00168', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00169', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00170', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00171', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00172', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00173', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPDC00174', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPGR00001', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00002', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00003', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00004', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00005', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00006', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00007', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00008', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00009', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00010', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00011', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00012', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00013', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00014', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00015', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00016', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00017', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00018', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPGR00019', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00020', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00021', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00022', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00023', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00024', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00025', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00026', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00027', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00028', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00029', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00030', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00031', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00032', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00033', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00034', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPGR00035', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00036', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00037', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00038', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00039', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00040', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00041', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00042', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00043', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00044', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00045', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00046', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00047', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00048', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00049', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00050', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00051', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00052', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00053', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00054', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00055', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00056', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00057', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00058', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00060', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00061', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPGR00062', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPGR00063', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPGR00064', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00065', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00066', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00067', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00068', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00069', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00070', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00071', 'local_church' => 'Granada'],
            ['lamp_card_number' => 'LPGR00072', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00073', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00074', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00075', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00076', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00077', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00078', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00079', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPGR00080', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPGR00081', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPGR00082', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00083', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00084', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00085', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00086', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00087', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00088', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00089', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00090', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPGR00091', 'local_church' => 'Hinigaran'],
            ['lamp_card_number' => 'LPVI00001', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00002', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00003', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00004', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00005', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00006', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00007', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00008', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00009', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00010', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00011', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00012', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00013', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00014', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00015', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00016', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00017', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00018', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00019', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00020', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00021', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00022', 'local_church' => 'Bacolod'],
            ['lamp_card_number' => 'LPVI00023', 'local_church' => 'Bacolod']
        ];

        foreach ($data as $arr) {
            $lookup = LookUp::where('lamp_card_number', $arr['lamp_card_number'])->first();

            $lookup->update([
                'local_church' => $arr['local_church']
            ]);

            $this->command->info('lookup ' . $lookup['lamp_card_number'] . ' -> ' . $lookup['local_church']);
        }
    }
}
